FROM alpine:latest

LABEL version="1.0"
LABEL description="softlayer event collector"
LABEL maintainer "daniel.rapp@se.ibm.com"
RUN apk update
RUN apk add ca-certificates
ADD collector /opt/collector
ENTRYPOINT ["/opt/collector"]